
var dict = {
    en: {
        'SITE-TITLE':'My name is Vitali, I am developing web sites and web presentations and other products.',
        'Purpose':'Purpose:',
        'Purse-Text':'Getting a position of a web developer.',
        'Professional-Skills':'Professional skills:',
        'Experience':'Experience:',
        'Experience-Content':'html coder, February 2017 - February 2018.',
        'Experience-Content-two':'web developer, February 2018 - December 2019.',
        'Experience-Content-three':'web-developer, October 2020 - present.',
        'Functional-Responsibilities':'Functional responsibilities:',
        'Responsibilities-Text1':'Adaptive cross-browser layout, layout of web application components sites.',
        // 'Responsibilities-Text2':'Development and support of existing projects.',
        'Responsibilities-Text2':'Development of themes on Word Press.',
        'Work-Html':'Coding "HTML":',
        'Work-Examples':'Work-Examples:',
        'Themes-WordPress':'Themes "WordPress":',
        'Applications-React':'"React" Application:',
        'Education':'Education:',
        'Education-One':'National Metallurgical Academy of Ukraine, Dnipro',
        'Education-Two':'Industrial College of Ukraine, Dnipro.',
        'Personal-Qualities':'Personal qualities:',
        'Qualities-Text':'Attentiveness, responsibility, technical thinking, poise, concentration, high degree of self- organization, discipline, focus on achieving results.',
        'HEADING-ONE':'About me:',
        'SOME-TEXT':'Some text in tag P',
        'ANOTHER-TEXT':'another text1',
        'First-Name':'Vitaliy',
        'Last-Name':'Nosov',
        'Write-Me':'WRITE ME',
        'Location':'Location:',
        'A-Country':'Ukraine',
        'City':'Dnepr',
        'Contact':'Contact:',
        'Social- Network':'Social network:',
        'languages':'Languages:',
        'English':'English',
        'Ru':'Rusian',
        'Ukr':'Ukranian',
        'Download':'Download:',
        'Email-Button':'Send',
        'Attach-File':'Attach file...'



    },
    ru: {
        'SITE-TITLE':'Меня зовут Виталий я занимаю разработкой веб-сайтов и веб-преложений и других продуктов.',
        'Purpose':'Цель:',
        'Purse-Text':'Получение должности веб-разработчика.',
        'Professional-Skills':'Профессиональные навыки:',
        'Experience':'Опыт работы:',
        'Experience-Content':'html coder, Февраль 2017 – Февраль 2018.',
        'Experience-Content-two':'web-developer, Февраль 2018 – Декабрь 2019.',
        'Experience-Content-three':'web-developer, Октябрь 2020 – настоящее время.',
        'Functional-Responsibilities':'Обязанности:',
        'Responsibilities-Text1':'Адаптивная кросс-браузерная верстка сайтов, верстка компонентов веб-приложений.',
        // 'Responsibilities-Text2': 'Разработка и поддержка существующих проектов.',
        'Responsibilities-Text2': 'Разработка тем на Word Press.',
        'Work-Examples':'Примеры работ:',
        'Work-Html':'Верстка "HTML":',
        'Themes-WordPress':'Темы на "Word Press":',
        'Applications-React':'Приложение на "React":',
        'Education':'Образование:',
        'Education-One':'Национальная металлургическая академия Украины, Днепр.',
        'Education-Two':'Индустриальный коледж Украины, Днепр.',
        'Personal-Qualities': 'Личные качества:',
        'Qualities-Text':'Внимательность, ответственность, техническое мышление, сосредоточенность, высокая степень самоорганизации, дисциплинированность, ориентированность на достижение результата.',
        'HEADING-ONE':'Обо мне:',
        'SOME-TEXT':'Some text in tag P',
        'ANOTHER-TEXT':'another text1',
        'First-Name':'Виталий',
        'Last-Name':'Носов',
        'Write-Me':'НАПИСАТЬ МНЕ',
        'Location':'Местоположение:',
        'A-Country':'Украина',
        'City':'Днепр',
        'Contact':'Контакты:',
        'Social- Network':'Социальные сети:',
        'languages':'Языки:',
        'English':'Английский',
        'Ru':'Русский',
        'Ukr':'Украинский',
        'Download':'Скачать:',
        'Email-Button':'Отправить',
        'Attach-File':'Прикрепить файл...'
    }
};